# Generated by Django 5.1.1 on 2024-10-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='male',
            name='girl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
        migrations.RemoveField(
            model_name='user_name',
            name='watch',
        ),
        migrations.DeleteModel(
            name='Female',
        ),
        migrations.DeleteModel(
            name='Male',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_name',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
