# Generated by Django 5.1.1 on 2024-10-02 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_loginuser_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loginuser',
            new_name='Login',
        ),
    ]
