# Generated by Django 5.1.1 on 2024-09-30 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_created_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 15, 36, 22, 995836)),
        ),
    ]
