# Generated by Django 5.1.1 on 2024-10-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_test_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
